author: croxis
database: true
description: Basic City/Nation plugin.
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: me.croxis.plugins.civilnations.Civilnations
name: CivilNations
startup: postworld
version: '1.0'
