author: croxis
database: true
description: Basic City/Nation plugin.
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: net.croxis.plugins.civilmineation.Civilmineation
name: Civilmineation
startup: postworld
version: '1.0'
commands:
    tech:
        aliases: []